version: '3.9'

services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DB_HOST: db  # Usa il nome del servizio 'db'
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: sql-db-1
    networks:
      - mynetwork

  db:
    image: mysql:latest
    container_name: sql-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql-db-1
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_AUTH_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-1
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
  static_volume:
  media_volume:
